language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
services:
  - mysql
dist: trusty
sudo: required
before_script:
  - export MYSQL_DATABASE=alpastor
  - export MYSQL_USERNAME=alpastoradmin
  - export MYSQL_USER_PASSWORD=alpastorpass
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS alpastor;'
  - mysql -u root -e "CREATE USER 'alpastoradmin'@'localhost' IDENTIFIED BY 'alpastorpass';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'alpastoradmin'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
script:
  - python alpastor/manage.py makemigrations
  - python alpastor/manage.py migrate
  - python alpastor/manage.py test alpastor/ -v 2
notifications:
  slack:
    rooms:
      secure: "JQ4UrPh0J4FWhzcLpvJZHZZGXErsAurQlhQH3GD8xZmVf79LfGNrP0dQXhD2pMq6HbET4cGW7AFmPrxyAZsYWpGAfJbm73DoXir8Cz7PXFBVtCmfX/gFcJDWWojeydhm/FdYxYT0m2/opWv5GO8OgzuH7F3dtEcdgFbydGotulerSKFFTc9FX5NjGck1lriRoogrxBYml8H9TOjDd9BnfMItpqXMCXvFS6K0yULx7eritEvsh8a2ZJNGaQ2QaU61c+zT2mSI9NLVBr1MZl6w8/tPiPVed/VVX+XYGV3CXAHsxjE7LCrFA1wPJylCb5oGf2ipWawmiHCE0O0v5hcWT9CWeXEb39dr6IwRf+73dl6AAm/SnL0E6JUuL9AwDkpNrRxzsV2ePmvDUsXUsj5BVE7furybDl0LVBLxe+yLSI0VvKgRQjDY3CC7L8zLNOxi7/hmjM/lp5iBQY82bx9NbZ4/kgjcrhgcCPt0SBuQTiZB6/Wo7SJCNQ/+wdsK8bEWNTM0hJl9uLoWl0Zvyn3cPbfaRYfN2mL/63maeL47Qr0C6HewcM9paKXli1OEsmXOzB58tJvcprlw2rf/HAb0BSs5NSlT50ve0hxhCZTXssPb+38ZDA8Aiz3xYNq1gp5s2iLYxu/2ib5x9TZqz6GuDziQOf1s6x/3wo3HP3lDEqc="
    on_success: always
    on_failure: always
