# Generated by Django 2.0.5 on 2018-06-11 13:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Excused')], default=2)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('semester', models.CharField(max_length=31)),
                ('module', models.CharField(blank=True, max_length=63)),
                ('credits', models.IntegerField()),
                ('slug', models.SlugField(default='course-slug', max_length=158)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=255)),
                ('points_earned', models.IntegerField()),
                ('points_possible', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
                ('photo_location', models.CharField(blank=True, max_length=511)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=datetime.datetime(2018, 6, 11, 15, 18, 52, 102088, tzinfo=utc))),
                ('attendance_closed', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
                ('program', models.IntegerField(choices=[(0, 'None'), (1, 'Master of Engineering'), (2, 'Master of Science'), (3, 'Global IT Management')], default=0)),
                ('specialization', models.IntegerField(choices=[(0, 'None'), (1, 'Software Engineering'), (2, 'Information Systems Management'), (3, 'Data Science & Analytics'), (4, 'Computer Security'), (5, 'Software Development & Multimedia'), (6, 'Systems Networks & Security')], default=0)),
                ('intakeSemester', models.CharField(max_length=31)),
                ('country', models.CharField(max_length=127)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=127)),
                ('languages', models.CharField(blank=True, max_length=127)),
                ('photo_location', models.CharField(blank=True, max_length=511)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Professor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'semester')},
        ),
    ]
