# Generated by Django 2.0.5 on 2018-06-28 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Excused')], default=2)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Course code e.g. ADVC123123', max_length=127)),
                ('title', models.CharField(help_text='Course title', max_length=127)),
                ('description', models.TextField(blank=True, help_text='Course description', max_length=1000)),
                ('semester', models.CharField(help_text='Season Year (e.g. Fall 2017)', max_length=31)),
                ('module', models.CharField(blank=True, help_text='Module or teaching unit', max_length=63)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='course-slug', max_length=158)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=255)),
                ('points_earned', models.IntegerField()),
                ('points_possible', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
                ('photo_location', models.CharField(blank=True, max_length=511)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=datetime.datetime(2018, 6, 28, 16, 32, 4, 176749, tzinfo=utc))),
                ('attendance_closed', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
                ('program', models.IntegerField(choices=[(0, 'None'), (1, 'Master of Engineering'), (2, 'Master of Science'), (3, 'Global IT Management (French)'), (4, 'Exchange')], default=0)),
                ('specialization', models.IntegerField(choices=[(0, 'None'), (1, 'Software Engineering'), (2, 'Information Systems Management'), (3, 'Data Science & Analytics'), (4, 'Computer Security'), (5, 'Software Development & Multimedia'), (6, 'Systems Networks & Security'), (7, 'Global IT Management (International)')], default=0)),
                ('intakeSemester', models.CharField(max_length=31)),
                ('country', models.CharField(max_length=127)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, help_text='City of origin', max_length=127)),
                ('languages', models.CharField(blank=True, max_length=127)),
                ('photo_location', models.CharField(blank=True, max_length=511, null=True)),
                ('address_street', models.CharField(blank=True, help_text='Street', max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, help_text='City', max_length=255, null=True)),
                ('address_misc', models.CharField(blank=True, help_text='Building, mailbox, etc.', max_length=255, null=True)),
                ('address_code', models.IntegerField(blank=True, help_text='Department code', null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('enrollment_status', models.IntegerField(choices=[(0, 'Enrolled'), (1, 'Withdrawn'), (2, 'Expelled'), (3, 'Graduated')], default=0, help_text='Enrollment status')),
                ('flags', models.IntegerField(choices=[(0, 'OK'), (1, 'Academic warning'), (2, 'Attendance warning')], default=0, help_text='Student flags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epita.Professor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epita.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'semester')},
        ),
    ]
