# Generated by Django 2.0.5 on 2018-07-12 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields
import epita.models


class Migration(migrations.Migration):

    dependencies = [
        ('epita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='photo_location',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo_location',
        ),
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, upload_to=epita.models.photo_file_path),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=epita.models.photo_file_path),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=epita.models.excuse_file_path),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2018, 7, 12, 10, 26, 38, 500365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_misc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(help_text='country', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.IntegerField(choices=[(0, 'Enrolled'), (1, 'Withdrawn'), (2, 'Expelled'), (3, 'Graduated')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='flags',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'Academic warning'), (2, 'Attendance warning')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
