# Generated by Django 2.0.5 on 2018-06-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classof',
            new_name='intakeSemester',
        ),
    ]
