# Generated by Django 2.0.2 on 2018-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epita', '0002_auto_20180228_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_location',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
