# Generated by Django 2.0.2 on 2018-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epita', '0004_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country_code',
            field=models.CharField(default='us', max_length=2),
            preserve_default=False,
        ),
    ]
