# Generated by Django 2.0.2 on 2018-03-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_squashed_0003_auto_20180328_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceoption',
            name='question',
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.MultipleChoiceQuestion', verbose_name='Multiple Choice Question'),
            preserve_default=False,
        ),
    ]
