# Generated by Django 2.0.5 on 2018-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Essay Question'), (1, 'Multiple Choice Question'), (2, 'Numeric Scale Question')], default=0, verbose_name='Question Type'),
        ),
    ]
