# Generated by Django 2.0.2 on 2018-03-28 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180328_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time'),
        ),
    ]
