# Generated by Django 2.0.2 on 2018-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180402_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericscalequestion',
            name='correct_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correct Value'),
        ),
    ]
