# Generated by Django 2.0.3 on 2018-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='external email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Professor'),
        ),
    ]
