# Generated by Django 2.0.2 on 2018-03-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180321_1115'),
        ('accounts', '0002_auto_20180321_1236'),
    ]

    operations = [
    ]
